version: "3"

services:
  db_postgres:
    image: postgres:11.5
    volumes:
      - ./data:/var/lib/postgresql/data
  
  backend:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres
    
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - backend
      
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

volumes:
  .:
  data:
  static: