# Generated by Django 3.1.6 on 2021-08-02 05:01

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_company', models.CharField(max_length=50)),
                ('description_company', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('market_values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]), size=50)),
            ],
        ),
    ]
