import uuid # Library that allows loading the autogenerated field with uuid
from django.db import models # allow load models
from django.contrib.postgres.fields import ArrayField # Method that allows using arrays in the database for market values

# Create your models here.
class Formulary(models.Model):
    """

    Args:
        models ([Web application displaying a form]): [

            These are the fields to load in the database
            to be saved and generate the crud
        
        ]

    Returns:
        [OBJECTS]: [
            Returns the objects that will be used to query
            and serialize for the creation of the crud
        ]
    """    

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name_company = models.CharField(max_length = 50)
    description_company = models.CharField(max_length = 100)
    symbol = models.CharField(max_length = 10)
    market_values = ArrayField(models.IntegerField(), size=50)

    def get_symbol(self):
        return self.name_company + ' Has as symbol ' + self.symbol

    def __str__(self):
        return self.name_company